[Trakt]
# Paste your credentials from https://trakt.tv/oauth/applications
ClientId = YOUR_CLIENT_ID_HERE
ClientSecret = YOUR_CLIENT_SECRET_HERE

# The get_trakt_token.py script will fill these in automatically
AccessToken =
RefreshToken =